Set up bookstore
c00p75/bookstore-cms pull request #1
Opened 2023-01-21 22:48 UTC by c00p75

- Initialise React app.
- Add routes

2023-01-21 22:54 UTC, emmiiorji requested changes
Hi @c00p75, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

![Invalid](https://user-images.githubusercontent.com/20554583/213890206-db578b84-916b-4f26-b199-1085fba4a29c.gif)

You have submitted a pull request that fails linter checks. Kindly fix the linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-21 23:59 UTC, Munsa1 requested changes
Hi @c00p75, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive readme file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-22 00:40 UTC, Reem-lab requested changes
# Hi @c00p75, 👋🏻👋🏻 

Good job so far! 💯🔥♻
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/SDunHzTgSZbSuQy1EP/giphy.gif"/>

## Highlights
- No Linters error ✅
- Followed Gitflow ✅
- Great working on the design ✅
- Professional README ✅🔥
- Descriptive PR ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-22 00:40 UTC, Reem-lab commented on src/components/bookCategories.js
> +  <h1>Cooming soon</h1>
- [ ] Great job on making the set up but I have a small note I think you forget to add a button here for check status as required in the requirements so i recommend to add it here 💯💯🔥😊
![image](https://user-images.githubusercontent.com/58553711/213895418-1bcc1706-0dd2-4f64-88ad-1e752a8fe0c5.png)

- Your project
![image](https://user-images.githubusercontent.com/58553711/213895432-e80f8e71-8cfa-455d-a624-e381bdb33d64.png)

2023-01-22 01:32 UTC, mirouhml approved these changes
# APPROVED 🟢

Hi @c00p75, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/ZdUnQS4AXEl1AERdil/giphy.gif?cid=ecf05e471p9juygtcaesd615kgxa3b2n2dt6xyrzcycnk4b3&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 13:21 UTC, merged